### ISSUE TITLE
Error de conexión

### ISSUE THREAD

**Issue by gvillafanetapia** [CarlosAyala/chilexpress-php-tarifaenvio#1]
Hola!
Quería saber si alguien está usando esto en la actualidad.

Intenté implementarlo para Magento pero al hacer la conexión con el WS recibo siempre el mismo error:
HTTP: Could not connect to host

Habrá cambiado algún parametro?

Gracias!

**Comment by gvillafanetapia** [comment]
Bueno recién pude validar en Postman que la URL esta bien, y responde.
Así que el problema viene por el lado del código o mi configuración del SoapClient.

**Comment by gvillafanetapia** [comment]
Lo que pasaba es que en algún momento el SoapClient internamente intentaba llamar el servicio a través de la siguiente ruta: http://qaws.ssichilexpress.cl:80/TarificarCourier

Lo resolví sobreescribiendo la función __doRequest de SoapClient usando curl y apuntando a http://qaws.ssichilexpress.cl/TarificarCourier?wsdl

**Comment by CarlosAyala** [comment]
Hola @gvillafanetapia 
Disculpa por no responderte, no me había dado cuenta que habías comentado.
La clase esta funcionando tal cual en un sitio que desarrolle y hasta ahora sin ningún problema. 
Quizás es por la versión de SOAP que no funciona bien?

Que bueno que lo pudiste solucionar.

**Comment by gvillafanetapia** [comment]
Puede ser.. parecería que esa URL la levanta del WSDL.
