### ISSUE TITLE
ECONNREFUSED

### ISSUE THREAD

**Issue by katusiky** [CarlosAyala/chilexpress-php-tarifaenvio#2]
Hola @CarlosAyala  Tengo una integración desde hace mucho tiempo ya con chilexpress, desde Node.

hace mas de 1 año funciona perfecto, pero desde hace mas o menos 1 mes y medio me dejo de funcionar en mi localhost, desde la app en producción funciona perfecto pero desde localhost me da el siguiente error:

`Error: connect ECONNREFUSED 200.31.35.84:80`

Alguna ayuda por favor?

Saludos

**Comment by CarlosAyala** [comment]
Hola,
Debes revisar tu conectividad, quizás tienes un firewall o algo así.
